#version 430 core
layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;

struct Particle {
    vec4 pos;
    vec4 vel;
};

layout(std430, binding = 0) buffer Particles {
    Particle p[];
};

layout(std430, binding = 1) buffer cellHeadBuffer {
    int cellHead[];
};

layout(std430, binding = 2) buffer particleNextBuffer {
    int particleNext[];
};

uniform float deltaTime;
uniform float radius;
uniform ivec2 gridRes;
uniform int phase;

float pi = 3.141592653589792;

float densityKernel(float influenceRadius, float dist) {
    float k = 4.0 / (pi * pow(influenceRadius, 8));
    float delta = influenceRadius * influenceRadius - dist * dist;
    return k * delta * delta * delta;
}

float computePressure(float stiffness, float targetDensity, float density) {
    return max(stiffness * (density - targetDensity), 0.0);
}

vec2 pressureGradient(vec2 dist, float influenceRadius) {
    float k = -30.0 / (pi * pow(influenceRadius, 5));
    float radiusValue = length(dist);
    float coeff = (influenceRadius - radiusValue) * (influenceRadius - radiusValue) / radiusValue;

    return coeff * dist;
}

vec2 pressureForce(
    vec2 dist,
    float influenceRadius,
    float mass,
    float pressure,
    float neighborPressure,
    float neighborDensity
) {
    vec2 grad = pressureGradient(dist, influenceRadius);
    float rhoj = max(neighborDensity, 1e-6);

    return - mass * (pressure + neighborPressure) / (2.0 * rhoj) * grad;
}

void main() {
    uint i = gl_GlobalInvocationID.x;

    // Global physics variables
    const float influenceRadius = radius * 2;
    const float cellSize = influenceRadius;
    
    const float mass = 1.0;
    const float stiffness = 200.0;
    const float targetDensity = 1000.0;
    const float collisionDamping = 0.4;
    const float gravity = 9.8;

    float density = 0.0;
    float pressure = 0.0;
    vec2 force = vec2(0.0, 0.0);

    // Filling the grid (linked list)
    vec2 pos = p[i].pos.xy;
    ivec2 cellCord = ivec2(floor((pos + vec2(1.0)) / cellSize));
    cellCord = clamp(cellCord, ivec2(0), gridRes - ivec2(1));
    int cellID = cellCord.x + cellCord.y * gridRes.x;

    // Filling the grid on phase 1
    if (phase == 0) {
        particleNext[i] = atomicExchange(cellHead[cellID], int(i));
        return;
    }

    // Calculating density on phase 2
    if (phase == 1) {
        for (int dx = -1; dx <= 1; dx++) {
            for (int dy = -1; dy <= 1; dy++) {
                ivec2 neighborCell = cellCord + ivec2(dx, dy);
                if (neighborCell.x < 0 
                    || neighborCell.x >= gridRes.x 
                    || neighborCell.y < 0 
                    || neighborCell.y >= gridRes.y)
                    continue;
                int neighborCellID = neighborCell.x + neighborCell.y * gridRes.x;
                int neighborIndex = cellHead[neighborCellID];

                while (neighborIndex != -1) { // While the cell is not empty
                    if (neighborIndex != int(i)) { // If the last particle is not itself
                        // Found a neighbor
                        vec3 neighborPos = p[neighborIndex].pos.xyz;
                        float delta = length(pos - neighborPos.xy);

                        if (delta < influenceRadius) {
                            // Calculating forces
                            density += mass * densityKernel(influenceRadius, delta);
                        }
                    }
                    neighborIndex = particleNext[neighborIndex];
                }
            }
        }

        p[i].pos.w = density;
        return;
    }

    // Calculating pressure on phase 2
    if (phase == 2) {
        pressure = computePressure(stiffness, targetDensity, p[i].pos.w);
        p[i].vel.w = pressure;
        return;
    }

    // Neighbor research
    for (int dx = -1; dx <= 1; dx++) {
        for (int dy = -1; dy <= 1; dy++) {
            ivec2 neighborCell = cellCord + ivec2(dx, dy);
            if (neighborCell.x < 0 
                || neighborCell.x >= gridRes.x 
                || neighborCell.y < 0 
                || neighborCell.y >= gridRes.y)
                continue;
            int neighborCellID = neighborCell.x + neighborCell.y * gridRes.x;
            int neighborIndex = cellHead[neighborCellID];
            
            while (neighborIndex != -1) { // While the cell is not empty
                if (neighborIndex != int(i)) { // If the last particle is not itself
                    // Found a neighbor
                    vec3 neighborPos = p[neighborIndex].pos.xyz;
                    float delta = length(pos - neighborPos.xy);

                    if (delta < influenceRadius) {
                        // Calculating forces
                        if (phase == 3) {
                            force += pressureForce(delta,
                            influenceRadius,
                            mass,
                            pressure,
                            p[neighborIndex].vel.w,
                            p[neighborIndex].pos.w
                            );
                        }
                    }
                }
                neighborIndex = particleNext[neighborIndex];
            }
        }
    }

    // Update and collisions
    force += vec2(0.0, -gravity * density);
    vec2 acc = force / density;
    p[i].vel.xy += acc * deltaTime;
    p[i].pos.xy += p[i].vel.xy * deltaTime;

    if (p[i].pos.x > 1.0 - radius || p[i].pos.x < radius - 1.0) {
        p[i].vel.x *= -collisionDamping;
        p[i].pos.x = (1.0 - radius) * sign(p[i].pos.x);
    }

    if (p[i].pos.y > 1.0 - radius || p[i].pos.y < radius - 1.0) {
        p[i].vel.y *= -collisionDamping;
        p[i].pos.y = (1.0 - radius) * sign(p[i].pos.y);
    }

    // Artificial friction
    p[i].vel.y *= 0.999;
    p[i].vel.x *= 0.999;
}
