#version 430 core
layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;

struct Particle {
    vec4 pos;
    vec4 vel;
};

struct Grid {
    float cellSize;
    uint cellResX;
    uint cellResY;
    uint cellTot;
};

layout(std430, binding = 0) buffer Particles {
    Particle p[];
};

layout(std430, binding = 1) buffer Grid {
    Grid grid;
};

uniform float deltaTime;
uniform float radius;

void main() {
    uint i = gl_GlobalInvocationID.x;

    // Variabili fisiche globali
    float influenceRadius = radius * 2;
    float cellSize = influenceRadius;

    // Variabili fisiche per particella

    p[i].pos.xyz += p[i].vel.xyz * deltaTime;

    if (p[i].pos.x > 1.0 - radius || p[i].pos.x < radius - 1.0) {
        p[i].vel.x *= -1;
        p[i].pos.x = (1.0 - radius) * sign(p[i].pos.x);
    }

    if (p[i].pos.y > 1.0 - radius || p[i].pos.y < radius - 1.0) {
        p[i].vel.y *= -1;
        p[i].pos.y = (1.0 - radius) * sign(p[i].pos.y);
    }
}
