#version 430 core
layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;

struct Particle {
    vec4 pos;
    vec4 vel;
};

layout(std430, binding = 0) buffer Particles {
    Particle p[];
};

layout(std430, binding = 1) buffer cellHeadBuffer {
    int cellHead[];
};

layout(std430, binding = 2) buffer particleNextBuffer {
    int particleNext[];
};

uniform float radius;
uniform ivec2 gridRes;
uniform int phase;

float pi = 3.141592653589792;

float densityKernel(float influenceRadius, float dist) {
    float k = 4.0 / (pi * pow(influenceRadius, 8));
    float delta = influenceRadius * influenceRadius - dist * dist;
    return k * delta * delta * delta;
}

float computePressure(float stiffness, float targetDensity, float density) {
    return max(stiffness * (density - targetDensity), 0.0);
}

vec2 pressureGradient(vec2 dist, float influenceRadius) {
    float k = -30.0 / (pi * pow(influenceRadius, 5));
    float radiusValue = max(length(dist), 1e-4);
    float coeff = (influenceRadius - radiusValue) * (influenceRadius - radiusValue) / radiusValue;

    return k * coeff * dist;
}

vec2 pressureForce(
    vec2 dist,
    float influenceRadius,
    float mass,
    float pressure,
    float neighborPressure,
    float neighborDensity
) {
    vec2 grad = pressureGradient(dist, influenceRadius);
    float rhoj = max(neighborDensity, 1e-6);

    return - mass * (pressure + neighborPressure) / (2.0 * rhoj) * grad;
}

void main() {
    uint i = gl_GlobalInvocationID.x;

    // Global physics variables
    const float influenceRadius = 0.013;
    const float cellSize = influenceRadius;
    const float mass = 0.013;
    const float stiffness = 200.0;
    const float targetDensity = 1000.0;
    const float collisionDamping = 0.4;
    const float gravity = 9.8;
    const float deltaTime = 0.0008;
    const float viscosity = 1.5;

    // Filling the grid (linked list)
    vec2 pos = p[i].pos.xy;
    ivec2 cellCord = ivec2(floor((pos + vec2(1.0)) / cellSize));
    cellCord = clamp(cellCord, ivec2(0), gridRes - ivec2(1));
    int cellID = cellCord.x + cellCord.y * gridRes.x;

    // Filling the grid on phase 1
    if (phase == 0) {
        particleNext[i] = atomicExchange(cellHead[cellID], int(i));
        return;
    }

    // Calculating density on phase 2
    if (phase == 1) {
        float density = 0.0;
        for (int dx = -1; dx <= 1; dx++) {
            for (int dy = -1; dy <= 1; dy++) {
                ivec2 neighborCell = cellCord + ivec2(dx, dy);
                if (neighborCell.x < 0 
                    || neighborCell.x >= gridRes.x 
                    || neighborCell.y < 0 
                    || neighborCell.y >= gridRes.y)
                    continue;
                int neighborCellID = neighborCell.x + neighborCell.y * gridRes.x;
                int neighborIndex = cellHead[neighborCellID];

                while (neighborIndex != -1) { // While the cell is not empty
                    vec2 neighborPos = p[neighborIndex].pos.xy;
                    float distScalar = length(pos - neighborPos);

                    if (distScalar < influenceRadius) 
                        density += mass * densityKernel(influenceRadius, distScalar);

                    neighborIndex = particleNext[neighborIndex];
                }
            }
        }

        p[i].pos.w = max(density, 1e-6); // Density
        p[i].vel.w = computePressure(stiffness, targetDensity, density); // Pressure
        return;
    }

    // Neighbor research
    if (phase == 2) {
        vec2 force = vec2(0.0, 0.0);
        float density = p[i].pos.w;
        float pressure = p[i].vel.w;

        for (int dx = -1; dx <= 1; dx++) {
            for (int dy = -1; dy <= 1; dy++) {
                ivec2 neighborCell = cellCord + ivec2(dx, dy);
                if (neighborCell.x < 0 
                    || neighborCell.x >= gridRes.x 
                    || neighborCell.y < 0 
                    || neighborCell.y >= gridRes.y)
                    continue;
                
                int neighborCellID = neighborCell.x + neighborCell.y * gridRes.x;
                int neighborIndex = cellHead[neighborCellID];

                while (neighborIndex != -1) { // While the cell is not empty
                    if (neighborIndex != int(i)) { // If the last particle is not itself
                        // Found a neighbor
                        vec2 neighborPos = p[neighborIndex].pos.xy;
                        vec2 distVec = pos - neighborPos;
                        float delta = length(distVec);

                        if (delta < influenceRadius && delta > 1e-6) {
                            // Calculating forces
                            // 1. pressure force
                            force += pressureForce(
                                distVec,
                                influenceRadius,
                                mass,
                                pressure,
                                p[neighborIndex].vel.w,
                                p[neighborIndex].pos.w
                            );

                            // 2. viscosity force
                            vec2 velDiff = p[neighborIndex].vel.xy - p[i].vel.xy;
                            float viscKernelLapl = (40.0 / (pi * pow(influenceRadius, 5.0))) * (influenceRadius - delta);
                            force += viscosity * mass * viscKernelLapl * (velDiff / max(p[neighborIndex].pos.w, 1e-6));
                        }
                    }
                    neighborIndex = particleNext[neighborIndex];
                }
            }
        }

        // Update and collisions
        force += vec2(0.0, -gravity * density);
        vec2 acc = force / density;
        p[i].vel.xy += acc * deltaTime;
        p[i].pos.xy += p[i].vel.xy * deltaTime;

        if (p[i].pos.x > 1.0 - radius || p[i].pos.x < radius - 1.0) {
            p[i].vel.x *= -collisionDamping;
            p[i].pos.x = (1.0 - radius) * sign(p[i].pos.x);
        }

        if (p[i].pos.y > 1.0 - radius || p[i].pos.y < radius - 1.0) {
            p[i].vel.y *= -collisionDamping;
            p[i].pos.y = (1.0 - radius) * sign(p[i].pos.y);
        }

        // Artificial friction
        p[i].vel.y *= 0.993;
        p[i].vel.x *= 0.993;
        return;
    }
}
