#version 430 core
layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;

struct Particle {
    vec4 pos;
    vec4 vel;
};

layout(std430, binding = 0) buffer Particles {
    Particle p[];
};

layout(std430, binding = 1) buffer cellHeadBuffer {
    int cellHead[];
};

layout(std430, binding = 2) buffer particleNextBuffer {
    int particleNext[];
};

uniform float deltaTime;
uniform float radius;
uniform ivec2 gridRes;
uniform bool phase;

void main() {
    uint i = gl_GlobalInvocationID.x;

    // Global physics variables
    float influenceRadius = radius * 2;
    float cellSize = influenceRadius;

    // Filling the grid (linked list)
    vec2 pos = p[i].pos.xy;
    ivec2 cellCord = ivec2(floor((pos + vec2(1.0)) / cellSize));
    cellCord = clamp(cellCord, ivec2(0), gridRes - ivec2(1));
    int cellID = cellCord.x + cellCord.y * gridRes.x;
    if (!phase) {
        particleNext[i] = atomicExchange(cellHead[cellID], int(i));
        return;
    }

    // Neighbor research
    for (int dx = -1; dx <= 1; dx++) {
        for (int dy = -1; dy <= 1; dy++) {
            ivec2 neighborCell = cellCord + ivec2(dx, dy);
            if (neighborCell.x < 0 
                || neighborCell.x >= gridRes.x 
                || neighborCell.y < 0 
                || neighborCell.y >= gridRes.y)
                continue;
            int neighborCellID = neighborCell.x + neighborCell.y * gridRes.x;
            int neighborIndex = cellHead[neighborCellID];
            
            while (neighborIndex != -1) { // While the cell is not empty
                if (neighborIndex != int(i)) { // If the last particle is not itself
                    // Found a neighbor
                    vec3 neighborPos = p[neighborIndex].pos.xyz;
                    float delta = length(pos - neighborPos.xy);

                    if (delta < influenceRadius) {
                        // Calculating forces
                    }
                }

                neighborIndex = particleNext[neighborIndex];
            }
        }
    }

    // Update and collisions

    p[i].pos.xyz += p[i].vel.xyz * deltaTime;

    if (p[i].pos.x > 1.0 - radius || p[i].pos.x < radius - 1.0) {
        p[i].vel.x *= -1;
        p[i].pos.x = (1.0 - radius) * sign(p[i].pos.x);
    }

    if (p[i].pos.y > 1.0 - radius || p[i].pos.y < radius - 1.0) {
        p[i].vel.y *= -1;
        p[i].pos.y = (1.0 - radius) * sign(p[i].pos.y);
    }
}
